---
- name: Adding Repo keys.
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    mode: '0644'
    dest: "{{ item.dest }}"
    force: true
  loop:
      - { url: 'https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key', dest: '/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg' }
      - { url: 'https://download.docker.com/linux/ubuntu/gpg', dest: '/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg' }
      - { url: 'https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg', dest: '/etc/apt/trusted.gpg.d/spotify-archive-keyring.gpg' }
      - { url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg', dest: '/etc/apt/trusted.gpg.d/google-cloud-sdk-keyring.gpg' }

# - name: Adding Repo keys
#  ansible.builtin.apt_key:
#    url: "{{ item }}"
#    state: present
#  loop:
#      - https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
#      - https://download.docker.com/linux/ubuntu/gpg
#      - https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
#      - https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Adding Repo URLs
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
      - "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
      - "deb [signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
      - "deb [signed-by=/etc/apt/trusted.gpg.d/spotify-archive-keyring.gpg] http://repository.spotify.com stable non-free"
      - "deb [signed-by=/etc/apt/trusted.gpg.d/google-cloud-sdk-keyring.gpg] https://packages.cloud.google.com/apt cloud-sdk main"

#- name: add key
#  apt_key:
#    url: "{{ item }}"
#    state: present
#  loop:
#    - https://download.docker.com/linux/ubuntu/gpg
#    - https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
#    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
#    - https://www.virtualbox.org/download/oracle_vbox_2016.asc

#- name: add repository
#  apt_repository:
#    repo: "{{ item }}"
#    state: present
#  loop:
#    - "ppa:ansible/ansible"
#    #- "ppa:gnome-terminator"
#    # - "deb https://download.docker.com/linux/ubuntu jammy stable"
#    # - "deb http://repository.spotify.com stable non-free"
#    - "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
#    # - "deb https://download.virtualbox.org/virtualbox/debian focal contrib"

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install a list of packages
  ansible.builtin.apt:
    name:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python
    - python3
    - btop
    - ansible
    #- python-pip-whl
    - python3-pip
    - terminator
    # - docker-ce
    # - virtualbox
    # - hollywood
    # - figlet
    - gcloud
    - kubectl
    - gnupg
    - curl
    - fzf
    # - virtualbox-ext-pack
    # - postman
    # - goland
    # - sublime

- name: Download DEB packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    # - { url: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb', dest: '/opt/' }
    # - { url: 'https://github.com/meetfranz/franz/releases/download/v5.1.0/franz_5.1.0_amd64.deb', dest: '/opt/' }
    #-  { url: 'https://downloads.slack-edge.com/releases/linux/4.31.155/prod/x64/slack-desktop-4.31.155-amd64.deb', dest: '/opt/' }
    # - { url: 'https://cdn.devolutions.net/download/Linux/RDM/2023.1.0.6/RemoteDesktopManager_2023.1.0.6_amd64.deb', dest: '/opt' }
    # - { url: 'https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb', dest: '/opt' }
    # - { url: 'https://github.com/ksnip/ksnip/releases/download/v1.10.1/ksnip-1.10.1.deb', dest: '/opt'}


- name: Install a .deb package
  apt:
    deb: /opt/{{ item }}
  loop:
    # - google-chrome-stable_current_amd64.deb
    # - franz_5.1.0_amd64.deb
    # - slack-desktop-4.31.155-amd64.deb
    # - RemoteDesktopManager_2023.1.0.6_amd64.deb
    # - vagrant_2.2.9_x86_64.deb
    # - ksnip-1.10.1.deb

- name: install pip modules
  pip:
    name: "{{ item }}"
  loop:
    - docker
    - boto
    - boto3
    - botocore
